#!/bin/bash
# patch - front-end job for patching remote servers

# *** remote-control metadata, parsed by rc
# Job configuration - the patch job will ask for confirmation before
# running.
#RCCONFIG:RCREQUIRECONFIRM="true";RCPROMPT="true"
# Initially required vars that must be set for the job to run.
# These may be modified by the depvars function.
#RCREQVARS="PATCHWHEN CONTACT PATCHHOST PRENOTIFY"
# Optional vars aren't required for the job to run, but their
# values will be shown for confirmation (when confirmation required)
#RCOPTVARS="ADMINMAIL FORCE"
# Definitions that must be in a *.defs file. If a defs file specifies
# a value for a required or optional variable, it will always override
# user input. TODO: check for this error condition
#RCREQDEFS="RCADMINMAIL PREPATCHSUBJECT PREPATCHMESSAGE POSTPATCHSUBJECT POSTPATCHMESSAGE"
# Variable specifications for user-supplied (not configured in a .defs file)
# vars. Format: #VARNAME:<pcre match regex>:(default value):<description>
# Note that ':' is illegal in the description (for syntax checking)
#ADMINMAIL:^[a-z_\d\.-]+\@[\da-z\.-]+\.[a-z\.]{2,6}$::From address on notifications, address to send sysadmin reports to
#FORCE:false|true:false:Patch host even when not required if set to "true"
#PRENOTIFY:false|true:false:Send notification before patching when set "true"
#NOTIFYWHEN:.*::When to send notification ('at' timespec)
#PATCHWHEN:.*::When to patch the host ('at' timespec)
#CONTACT:^[a-z_\d\.-]+\@[\da-z\.-]+\.[a-z\.]{2,6}$::Contact for the host that receives notifications
#PATCHHOST:[\da-z\.-]+::The host to be patched
# *** end of rc metadata

# This job should do pre-flight check, then schedule the dopatch job

usage(){
	cat <<"EOF"
Usage: patch (FORCE=true) (PRENOTIFY=true) (NOTIFYWHEN=<timespec>) \
	(PATCHWHEN=<timespec>) CONTACT=<email> PATCHHOST=<host>

Patch a system at the given time, sending pre-(if configured) and post-
notifications to CONTACT.
EOF
	exit ${1:-1}
}

if [ "$1" = "help" -o "$1" = "-h" ]
then
	usage 0
fi

# Depvars should handle dependencies between variables and error checking
# of values
depvars(){
	if [ "$PRENOTIFY" = "true" ]
	then
		addrequired NOTIFYWHEN
	else
		removerequired NOTIFYWHEN
	fi
}

# Now let rc lib handle var checking, prompting, confirmation, regex matching,
# etc.
processvars

# Default ADMINMAIL to RCADMINMAIL if ADMINMAIL wasn't passed in
ADMINMAIL=${ADMINMAIL:-$RCADMINMAIL}

# Sanity check - can the host even be reached?
status "Checking connectivity to $PATCHHOST..."
#rcdo ping $PATCHHOST || { echo "Unable to reach $PATCHHOST"; exit 1; }
rcdo ping $PATCHHOST
echo "OK"

if [ "$FORCE" != "true" ]
then
	status "Checking if patches are needed..."
	# It's normal to get an error return from yumcheck
	set +e
	trap - ERR
	rcdo yumcheck $PATCHHOST
	YCRETVAL=$?
	set -e
	jobtrap # alias defined in libslocal/errhandle.sh
	if [ $YCRETVAL -eq 100 ]
	then
		echo "Patching is required"
	elif [ $YCRETVAL -eq 0 ]
	then
		echo "No patching required; set FORCE=\"true\" to force"
		exit 0
	else
		echo "Error $YCRETVAL returned from yum check-update, aborting."
		exit 1
	fi
fi

# If the user is to be notified ahead of time (-n used),
# schedule the at job.
if [ "$PRENOTIFY" = "true" ]
then
	status "Pre-notification requested, setting up automated email for \"$NOTIFYWHEN\""
	eval PREPATCHSUBJECT=\""$PREPATCHSUBJECT"\"
	eval PREPATCHMESSAGE=\""$PREPATCHMESSAGE"\"
	NOTIFYJOB=$(cat <<EOF
mail -r $ADMINMAIL -s "$PREPATCHSUBJECT" $CONTACT <<MEOF
$PREPATCHMESSAGE
MEOF
EOF
)
	echo "job: at $NOTIFYWHEN"
	cat <<<"$NOTIFYJOB"
	at $NOTIFYWHEN <<<"$NOTIFYJOB"
	echo "Done"
fi

# Schedule the actual patch job

PATCHJOB=$(cat <<EOF
rcrun dopatch "ADMINMAIL=$ADMINMAIL" "CONTACT=$CONTACT" PATCHHOST=$PATCHHOST
EOF
)
status "Scheduling patching job at \"$PATCHWHEN\""
echo "job: at $PATCHWHEN"
cat <<<"$PATCHJOB"
at $PATCHWHEN <<<"$PATCHJOB"
exit 0
