#!/bin/bash
# patch - front-end job for patching remote servers
#RCJOBREQUIREVARS="PATCHWHEN CONTACT PATCHHOST"
# This job should do pre-flight check, then schedule the dopatch job

source $RCROOT/libslocal/common.sh

usage(){
	cat <<EOF
Usage: patch (FORCE=true) (PRENOTIFY=true) (NOTIFYWHEN=<timespec>) \
	(PATCHWHEN=<timespec>) CONTACT=<email> PATCHHOST=<host>

Patch a system at the given time, sending pre-(if configured) and post-
notifications to CONTACT.
EOF
	exit 1
}

rcrequired(){
	cat <<"EOF"
~/.rcconfig required with:
RCADMINMAIL - optional, can be supplied with -a option
PREPATCHSUBJECT - optional, if pre-patch notification sent
PREPATCHMESSAGE - optional, if pre-patch notification sent
POSTPATCHSUBJECT
POSTPATCHMESSAGE

See example-conf/HOME.rcconfig
EOF
	exit 1
}

# Source the standard ~/.rcconfig, required for patch/dopatch
if [ -e ~/.rcconfig ]
then
	source ~/.rcconfig
else
	rcrequired
fi

# Use bash getopts built-in for argument parsing
while getopts ":a:fhn:" OPT
do
	case $OPT in
	a)
		RCADMINMAIL=${OPTARG}
		MAILARG="-a $RCADMINMAIL"
		;;
	f)
		FORCEPATCHING="true"
		;;
    h)
		usage
		;;
	n)
		PRENOTIFY="${OPTARG}"
		;;
    :)
		echo "Option -$OPTARG requires an argument." >&2
		usage
		;;
    \?)
		echo "Invalid option: -$OPTARG" >&2
		usage
		;;
	esac
done

# Shift away options so that required command arguments are now in $@
shift $((OPTIND-1))

[ $# -ne 3 ] && usage
[ -z "$RCADMINMAIL" ] && { echo "RCADMINMAIL undefined!"; rcrequired; }
[ -z "$PREPATCHSUBJECT" ] && { echo "PREPATCHSUBJECT undefined!"; rcrequired; }
[ -z "$PREPATCHMESSAGE" ] && { echo "PREPATCHMESSAGE undefined!"; rcrequired; }
[ -z "$POSTPATCHSUBJECT" ] && { echo "POSTPATCHSUBJECT undefined!"; rcrequired; }
[ -z "$POSTPATCHMESSAGE" ] && { echo "POSTPATCHMESSAGE undefined!"; rcrequired; }

TIMESPEC="$1"
CONTACT="$2"
PATCHHOST=$3
HOSTCOUNT=($PATCHHOST)
[ ${#HOSTCOUNT[@]} -gt 1 ] && { echo "Can only run patch on a single host at a time"; usage; }

# Sanity check - can the host even be reached?
status "Checking connectivity to $PATCHHOST..."
rcdo ping $PATCHHOST || { echo "Unable to reach $PATCHHOST"; exit 1; }
echo "OK"

if [ -z "$FORCEPATCHING" ]
then
	status "Checking if patches are needed..."
	set +e
	rcdo yumcheck $PATCHHOST
	YCRETVAL=$?
	set -e
	if [ $YCRETVAL -eq 100 ]
	then
		echo "Patching is required"
	elif [ $YCRETVAL -eq 0 ]
	then
		echo "No patching required; use -f to force"
		exit 0
	else
		echo "Error $YCRETVAL returned from yum check-update, aborting."
		exit 1
	fi
fi

# If the user is to be notified ahead of time (-n used),
# schedule the at job.
if [ -n "$PRENOTIFY" ]
then
	status "Pre-notification requesting, setting up automated email for \"$PRENOTIFY\""
	eval PREPATCHSUBJECT=\""$PREPATCHSUBJECT"\"
	eval PREPATCHMESSAGE=\""$PREPATCHMESSAGE"\"
	NOTIFYJOB=$(cat <<EOF
mail -r $RCADMINMAIL -s "$PREPATCHSUBJECT" $CONTACT <<MEOF
$PREPATCHMESSAGE
MEOF
EOF
)
	echo "job: at $PRENOTIFY"
	cat <<<"$NOTIFYJOB"
	at $PRENOTIFY <<<"$NOTIFYJOB"
	echo "Done"
fi

# Schedule the actual patch job

PATCHJOB=$(cat <<EOF
rcrun dopatch $MAILARG "$CONTACT" $PATCHHOST
EOF
)
status "Scheduling patching job at \"$TIMESPEC\""
echo "job: at $TIMESPEC"
cat <<<"$PATCHJOB"
at $TIMESPEC <<<"$PATCHJOB"
exit 0
